import { describe, expect, it } from 'vitest';
import { bunLockParser, yarnLockParser } from '../src/index.js';

const YARN_V1 = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.0.0":
  version "7.12.11"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.12.11.tgz#abc"
  integrity sha512-babel
  dependencies:
    "@babel/highlight" "^7.10.4"

lodash@^4.17.20, lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#def"
  integrity sha512-lodash
`;

const YARN_BERRY = `__metadata:
  version: 6
  cacheKey: 8

"lodash@npm:^4.17.20":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: abc123
  languageName: node
  linkType: hard

"@scope/thing@npm:^1.0.0":
  version: 1.2.0
  resolution: "@scope/thing@npm:1.2.0"
  dependencies:
    lodash: "npm:^4.17.20"
  languageName: node
  linkType: hard
`;

describe('yarnLockParser', () => {
  it('parses the classic v1 format', () => {
    const parsed = yarnLockParser.parse(YARN_V1, 'yarn.lock');
    expect(parsed.formatVersion).toBe('1');
    const lodash = parsed.packages.find((pkg) => pkg.name === 'lodash');
    expect(lodash?.version).toBe('4.17.21');
    expect(lodash?.integrity).toBe('sha512-lodash');
  });

  it('reads indented dependency entries in v1', () => {
    const parsed = yarnLockParser.parse(YARN_V1, 'yarn.lock');
    const babel = parsed.packages.find((pkg) => pkg.name === '@babel/code-frame');
    expect(babel?.dependencies).toEqual({ '@babel/highlight': '^7.10.4' });
  });

  it('parses the berry YAML format', () => {
    const parsed = yarnLockParser.parse(YARN_BERRY, 'yarn.lock');
    expect(parsed.formatVersion).toBe('6');
    const lodash = parsed.packages.find((pkg) => pkg.name === 'lodash');
    expect(lodash?.version).toBe('4.17.21');
    const thing = parsed.packages.find((pkg) => pkg.name === '@scope/thing');
    expect(thing?.dependencies).toEqual({ lodash: '^4.17.20' });
  });
});

const BUN_LOCK = `{
  "lockfileVersion": 0,
  "workspaces": {
    "": {
      "name": "app",
      "dependencies": { "lodash": "^4.17.21" },
      "devDependencies": { "typescript": "^5.0.0" }
    }
  },
  "packages": {
    "lodash": ["lodash@4.17.21", "", {}, "sha512-lodash"],
    "typescript": ["typescript@5.4.0", "", {}, "sha512-ts"]
  }
}`;

describe('bunLockParser', () => {
  it('parses workspaces and package tuples', () => {
    const parsed = bunLockParser.parse(BUN_LOCK, 'bun.lock');
    expect(parsed.imports.map((entry) => `${entry.name}:${entry.kind}`).sort()).toEqual([
      'lodash:prod',
      'typescript:dev',
    ]);
    expect(parsed.packages.map((pkg) => `${pkg.name}@${pkg.version}`).sort()).toEqual([
      'lodash@4.17.21',
      'typescript@5.4.0',
    ]);
    expect(parsed.packages.find((pkg) => pkg.name === 'lodash')?.integrity).toBe('sha512-lodash');
  });

  it('tolerates trailing commas and comments', () => {
    const withComments = `{
      // bun writes JSONC
      "lockfileVersion": 0,
      "workspaces": { "": { "name": "app", "dependencies": { "lodash": "^4.0.0" }, }, },
      "packages": { "lodash": ["lodash@4.17.21", "", {}, "sha512-x"], },
    }`;
    expect(bunLockParser.parse(withComments, 'bun.lock').packages).toHaveLength(1);
  });
});
