import { DeplyzeError, ErrorCode, Logger, redactSecrets, type Finding } from '@deplyze/core';
import type { ResolvedConfig } from '@deplyze/config';
import type { ScanResult } from '@deplyze/scanners';
import { UNTRUSTED_DATA_INSTRUCTION, createProvider, fenceUntrusted, type AiProvider } from './provider.js';
import { BASE_SYSTEM_PROMPT, minimizeContext, minimizeFinding, systemPromptFor } from './context.js';

export interface AiResult {
  /** AI-generated text. Always labelled as AI-generated by callers. */
  text: string;
  provider: string;
  model: string;
  /** Human-readable description of exactly what was transmitted. */
  disclosure: string;
  usage?: { inputTokens?: number; outputTokens?: number };
}

export interface AiRunnerOptions {
  config: ResolvedConfig;
  logger?: Logger;
  provider?: AiProvider;
}

/**
 * Runs optional AI analysis on top of deterministic results.
 *
 * Deplyze never requires this class: every command that uses it has a
 * deterministic fallback, and the AI layer only ever *adds* explanation.
 */
export class AiRunner {
  private readonly config: ResolvedConfig;
  private readonly logger: Logger;
  private readonly injected?: AiProvider;
  private resolved?: AiProvider;

  constructor(options: AiRunnerOptions) {
    this.logger = options.logger ?? new Logger({ level: 'silent' });
    this.config = options.config;
    if (options.provider) this.injected = options.provider;
  }

  /**
   * Create the provider lazily. Construction must never fail for a project with
   * AI disabled: `deplyze remediate` and friends are expected to fall back to
   * the deterministic path, and throwing here would make that impossible.
   */
  private get provider(): AiProvider {
    this.resolved ??= this.injected ?? createProvider({ config: this.config.ai, logger: this.logger });
    return this.resolved;
  }

  get enabled(): boolean {
    return this.config.ai.enabled && this.config.ai.provider !== 'none';
  }

  private async call(system: string, user: string, disclosure: string): Promise<AiResult> {
    const result = await this.provider.complete({
      system,
      user: redactSecrets(user),
      maxTokens: this.config.ai.maxTokens,
      temperature: this.config.ai.temperature,
    });
    const payload: AiResult = {
      text: result.text,
      provider: result.provider,
      model: result.model,
      disclosure,
    };
    if (result.usage) payload.usage = result.usage;
    return payload;
  }

  async explain(result: ScanResult, finding: Finding): Promise<AiResult> {
    const context = minimizeFinding(result, finding);
    const user = `Analyse this Deplyze finding.\n\n${fenceUntrusted(JSON.stringify(context, null, 2))}`;
    return this.call(
      systemPromptFor('explain', UNTRUSTED_DATA_INSTRUCTION),
      user,
      `Sent one finding (${finding.id}) and project metadata. No source code was transmitted.`,
    );
  }

  async remediate(result: ScanResult): Promise<AiResult> {
    const context = minimizeContext(result, result.findings);
    const user =
      `Produce a remediation plan for this project.\n\n` +
      fenceUntrusted(
        JSON.stringify({ summary: context.project, risk: context.risk, findings: context.findings }, null, 2),
      );
    return this.call(systemPromptFor('remediate', UNTRUSTED_DATA_INSTRUCTION), user, context.disclosure);
  }

  async upgradePlan(result: ScanResult): Promise<AiResult> {
    const upgradeFindings = result.findings.filter(
      (finding) => finding.category === 'outdated' || finding.category === 'vulnerability',
    );
    const context = minimizeContext(result, upgradeFindings);
    const user = `Produce an upgrade plan.\n\n${fenceUntrusted(JSON.stringify({ risk: context.risk, findings: context.findings }, null, 2))}`;
    return this.call(systemPromptFor('upgradePlan', UNTRUSTED_DATA_INSTRUCTION), user, context.disclosure);
  }

  async review(result: ScanResult): Promise<AiResult> {
    const context = minimizeContext(result, result.findings);
    const user = `Review this dependency posture.\n\n${fenceUntrusted(JSON.stringify(context, null, 2))}`;
    return this.call(systemPromptFor('review', UNTRUSTED_DATA_INSTRUCTION), user, context.disclosure);
  }

  /** Deterministic fallback used when AI is disabled. */
  static fallback(finding: Finding): string {
    const lines: string[] = [];
    lines.push(`${finding.severity.toUpperCase()} · ${finding.title}`);
    lines.push('');
    lines.push(finding.description);
    lines.push('');
    lines.push('Evidence:');
    for (const evidence of finding.evidence) lines.push(`  - ${evidence.message}`);
    if (finding.remediation) {
      lines.push('');
      lines.push(`Recommended action: ${finding.remediation.summary}`);
      if (finding.remediation.command) lines.push(`  ${finding.remediation.command}`);
      for (const step of finding.remediation.steps ?? []) lines.push(`  - ${step}`);
    }
    lines.push('');
    lines.push('(Deterministic explanation. Enable AI in .deplyze.yml for an AI-authored analysis.)');
    return lines.join('\n');
  }
}

export function assertAiEnabled(config: ResolvedConfig): void {
  if (!config.ai.enabled || config.ai.provider === 'none') {
    throw new DeplyzeError(ErrorCode.DEPLYZE_E_AI_DISABLED, 'AI features are disabled.', {
      hint: 'Deplyze is fully functional without AI. To enable it, set ai.enabled: true and ai.provider in .deplyze.yml.',
    });
  }
}

export { BASE_SYSTEM_PROMPT };
