import { createHash } from 'node:crypto';
import type { DependencyGraph } from '@deplyze/core';
import type { ScanResult } from '@deplyze/scanners';
import { normalizeLicenseId, parseLicenseExpression, collectLicenseIds } from '@deplyze/scanners';
import { purlFor, sriToHex } from './purl.js';

export interface SpdxOptions {
  /** Deterministic document namespace (tests, reproducible pipelines). */
  namespace?: string;
  created?: string;
  /** SPDX `name` of the document. */
  name?: string;
}

export function spdxIdFor(prefix: string, value: string): string {
  const safe = value.replace(/[^A-Za-z0-9.-]/g, '-').replace(/-+/g, '-');
  const hash = createHash('sha1').update(value).digest('hex').slice(0, 8);
  return `SPDXRef-${prefix}-${safe}-${hash}`;
}

function concludedLicense(raw: string | undefined): string {
  if (!raw) return 'NOASSERTION';
  const parsed = parseLicenseExpression(raw);
  const ids = (parsed ? collectLicenseIds(parsed) : [normalizeLicenseId(raw)]).filter((id) =>
    /^[A-Za-z0-9.+-]+$/.test(id),
  );
  return ids.length > 0 ? ids.join(' AND ') : 'NOASSERTION';
}

export function buildSpdx(result: ScanResult, options: SpdxOptions = {}): Record<string, unknown> {
  const graph: DependencyGraph = result.graph;
  const created = options.created ?? result.finishedAt;
  const namespaceHash = createHash('sha256')
    .update(`${result.project.root}|${result.project.name}|${result.project.version ?? ''}`)
    .digest('hex')
    .slice(0, 32);

  const rootSpdxId = spdxIdFor('Package', result.project.name);
  const packages: Array<Record<string, unknown>> = [
    {
      SPDXID: rootSpdxId,
      name: result.project.name,
      versionInfo: result.project.version ?? 'NOASSERTION',
      downloadLocation: 'NOASSERTION',
      filesAnalyzed: false,
      licenseConcluded: 'NOASSERTION',
      licenseDeclared: 'NOASSERTION',
      copyrightText: 'NOASSERTION',
      supplier: 'NOASSERTION',
    },
  ];

  const spdxIds = new Map<string, string>();
  for (const node of graph.nodes()) {
    if (node.depth === 0) continue;
    const id = spdxIdFor('Package', `${node.ecosystem}-${node.name}@${node.version}`);
    spdxIds.set(node.id, id);
    const entry: Record<string, unknown> = {
      SPDXID: id,
      name: node.name,
      versionInfo: node.version,
      downloadLocation: node.resolved ?? 'NOASSERTION',
      filesAnalyzed: false,
      licenseConcluded: concludedLicense(node.license),
      licenseDeclared: concludedLicense(node.license),
      copyrightText: 'NOASSERTION',
      supplier: 'NOASSERTION',
      externalRefs: [
        {
          referenceCategory: 'PACKAGE-MANAGER',
          referenceType: 'purl',
          referenceLocator: purlFor(node),
        },
      ],
    };
    if (node.integrity) {
      const hash = sriToHex(node.integrity);
      if (hash) {
        const algorithm = hash.algorithm.replace('SHA-', 'SHA');
        entry.checksums = [{ algorithm, checksumValue: hash.hex }];
      }
    }
    packages.push(entry);
  }

  const relationships: Array<Record<string, unknown>> = [
    {
      spdxElementId: 'SPDXRef-DOCUMENT',
      relationshipType: 'DESCRIBES',
      relatedSpdxElement: rootSpdxId,
    },
  ];

  for (const node of graph.nodes()) {
    if (node.depth === 0) {
      for (const dependent of node.dependencies) {
        const target = spdxIds.get(dependent);
        if (target) {
          relationships.push({
            spdxElementId: rootSpdxId,
            relationshipType: 'DEPENDS_ON',
            relatedSpdxElement: target,
          });
        }
      }
      continue;
    }
    const sourceId = spdxIds.get(node.id);
    if (!sourceId) continue;
    for (const dependency of node.dependencies) {
      const targetId = spdxIds.get(dependency);
      if (targetId) {
        relationships.push({
          spdxElementId: sourceId,
          relationshipType: 'DEPENDS_ON',
          relatedSpdxElement: targetId,
        });
      }
    }
  }

  return {
    spdxVersion: 'SPDX-2.3',
    dataLicense: 'CC0-1.0',
    SPDXID: 'SPDXRef-DOCUMENT',
    name: options.name ?? `${result.project.name}-${result.project.version ?? '0.0.0'}`,
    documentNamespace: options.namespace ?? `https://deplyze.dev/spdx/${namespaceHash}`,
    creationInfo: {
      created,
      creators: ['Tool: deplyze-0.1.0'],
      comment:
        'Generated by Deplyze from the resolved dependency graph. Absence of a field means Deplyze had no evidence for it (NOASSERTION), not that the value is empty.',
    },
    packages,
    relationships,
  };
}
